### PR TITLE
Add Iterate Dev Conf

### PR DESCRIPTION
**Pull request by vutran**

### CODE REVIEW

**Comment by prigara** [comment]
Hi, @vutran!
Thanks for sending a PR. Unfortunately, the URL didn't work for me and I wasn't able to find the conference in search. Can you please send a correct link?

**Comment by vutran** [comment]
Uh, it looks like the recently changed the name of the day conf and not sure why. Will update this PR.

**Comment by prigara** [comment]
Thanks! It seems to be not very much JavaScript-focused. Would you mind if I add it to the list of General conferences instead?

**Comment by vutran** [comment]
Sure!

**Pull request closed without merging**
