### PR TITLE
Added ReactNext 2018

### PR DESCRIPTION
**Pull request by trivikr**

### CODE REVIEW

**Comment by nimzco** [comment]
Where did you get the 2018 date? I don't see anything on their twitter or their website?

**Comment by trivikr** [comment]
Looks like I added 2017 dates by mistake, thanks for the catch!
2018 dates are displayed at https://www.eventbrite.com/e/reactnext-2018-tickets-39688618727, I've updated the commit.

**Comment by trivikr** [comment]
Confirmed that 2018-09-06 is updated as their cover photo on Facebook https://www.facebook.com/ReactNext2016

**Comment by nimzco** [comment]
Oh nice! I've just [tweeted a them](https://twitter.com/nimz_co/status/902272217081417728) hoping they will update their website. If not, we can link to the eventbrite. 👍

**Pull request merged**
